"""Domain enums for pair lifecycle, journaling, and reconciliation."""

from __future__ import annotations

from enum import Enum


class PairStatus(str, Enum):
    PENDING = "PENDING"
    ENTRY_SENT = "ENTRY_SENT"
    ENTRY_MT5_FILLED = "ENTRY_MT5_FILLED"
    ENTRY_EXCHANGE_FILLED = "ENTRY_EXCHANGE_FILLED"
    OPEN = "OPEN"
    CLOSE_SENT = "CLOSE_SENT"
    CLOSE_MT5_DONE = "CLOSE_MT5_DONE"
    CLOSE_EXCHANGE_DONE = "CLOSE_EXCHANGE_DONE"
    CLOSED = "CLOSED"
    FAILED = "FAILED"
    ORPHAN_MT5 = "ORPHAN_MT5"
    ORPHAN_EXCHANGE = "ORPHAN_EXCHANGE"
    HEALING = "HEALING"
    HEALED = "HEALED"
    FORCE_CLOSED = "FORCE_CLOSED"


class PairEventType(str, Enum):
    CREATED = "CREATED"
    ENTRY_DISPATCHED = "ENTRY_DISPATCHED"
    MT5_FILLED = "MT5_FILLED"
    EXCHANGE_FILLED = "EXCHANGE_FILLED"
    ENTRY_COMPLETE = "ENTRY_COMPLETE"
    ENTRY_FAILED = "ENTRY_FAILED"
    ENTRY_PARTIAL = "ENTRY_PARTIAL"
    CLOSE_DISPATCHED = "CLOSE_DISPATCHED"
    MT5_CLOSED = "MT5_CLOSED"
    EXCHANGE_CLOSED = "EXCHANGE_CLOSED"
    CLOSE_COMPLETE = "CLOSE_COMPLETE"
    CLOSE_PARTIAL_FAIL = "CLOSE_PARTIAL_FAIL"
    STOPOUT_DETECTED = "STOPOUT_DETECTED"
    LIQUIDATION_DETECTED = "LIQUIDATION_DETECTED"
    RECON_OK = "RECON_OK"
    RECON_MISMATCH = "RECON_MISMATCH"
    HEAL_START = "HEAL_START"
    HEAL_SUCCESS = "HEAL_SUCCESS"
    HEAL_FAILED = "HEAL_FAILED"
    FORCE_CLOSE = "FORCE_CLOSE"


class ReconStatus(str, Enum):
    PENDING = "PENDING"
    OK = "OK"
    MISMATCH = "MISMATCH"
    ORPHAN_MT5 = "ORPHAN_MT5"
    ORPHAN_EXCHANGE = "ORPHAN_EXCHANGE"
    HEALED = "HEALED"


class CloseReason(str, Enum):
    SIGNAL = "SIGNAL"
    HOLD_TIMEOUT = "HOLD_TIMEOUT"
    FORCE_SCHEDULE = "FORCE_SCHEDULE"
    FORCE_SHUTDOWN = "FORCE_SHUTDOWN"
    HEAL_ORPHAN_MT5 = "HEAL_ORPHAN_MT5"
    HEAL_ORPHAN_EXCHANGE = "HEAL_ORPHAN_EXCHANGE"
    HEAL_GHOST = "HEAL_GHOST"
    MANUAL = "MANUAL"

